export function generateMockProof(
  loanAmount: number,
  invoiceId: string,
  dueDate: string
): Uint8Array {
  // 1. Create the proof payload (normally generated by Noir/RISC Zero).
  // The verifier extracts the last 256 bytes as 8 public inputs (32 bytes each).
  
  // Create a mock "proof" of arbitrary length, say 1024 bytes.
  const proofLength = 1024;
  const proof = new Uint8Array(proofLength);
  
  // Fill the beginning with some random mock data (the actual "proof")
  for (let i = 0; i < proofLength - 256; i++) {
    proof[i] = Math.floor(Math.random() * 256);
  }

  // Helper to write a 32-byte hex string to the array at a specific offset
  const writeField = (hexStr: string, offset: number) => {
    // Ensure the hex string is exactly 64 characters (32 bytes)
    const cleanHex = hexStr.replace("0x", "").padStart(64, "0");
    for (let i = 0; i < 32; i++) {
      proof[offset + i] = parseInt(cleanHex.substring(i * 2, i * 2 + 2), 16);
    }
  };

  const publicInputsOffset = proofLength - 256;

  // Field 1: nullifier (mocked)
  writeField("0000000000000000000000000000000000000000000000000000000000000001", publicInputsOffset);
  
  // Field 2: invoice_hash (mocked based on id)
  writeField("0000000000000000000000000000000000000000000000000000000000000002", publicInputsOffset + 32);
  
  // Field 3: loan_amount
  const loanHex = loanAmount.toString(16);
  writeField(loanHex, publicInputsOffset + 64);
  
  // Field 4: ltv_bps (e.g. 8000 = 80%)
  const ltvHex = (8000).toString(16);
  writeField(ltvHex, publicInputsOffset + 96);
  
  // Field 5: interest_bps (e.g. 500 = 5%)
  const interestHex = (500).toString(16);
  writeField(interestHex, publicInputsOffset + 128);
  
  // Field 6: provider_response_hash
  writeField("0000000000000000000000000000000000000000000000000000000000000006", publicInputsOffset + 160);
  
  // Field 7: padding
  writeField("0000000000000000000000000000000000000000000000000000000000000000", publicInputsOffset + 192);
  
  // Field 8: padding
  writeField("0000000000000000000000000000000000000000000000000000000000000000", publicInputsOffset + 224);

  return proof;
}
